#!/bin/bash

container_name="symfony-docker-gonetil-php-1"
docker exec -it $container_name sh -c "curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.alpine.sh' | bash"
docker exec -it $container_name apk add symfony-cli
alias symfony='docker exec -it $container_name symfony'
